### ISSUE TITLE
Rename the repository

### ISSUE THREAD

**Issue by hroncok** [fedora-python/taskotron-python-versions#10]
We'd like to rename this repository to **taskotron-python-versions**, GitHub should handle the redirecting well, but I'd still like to coordinate with Fedora QA and change the repository URL in the taskotron instances as well.

@kparal What do I do?

**Comment by kparal** [comment]
Rename the repo and ping me, we'll fix the links.

**Comment by kparal** [comment]
Asked @mkrizek to fix the links.

**Comment by mkrizek** [comment]
Should be fixed.

**Comment by hroncok** [comment]
Thanks
