### ISSUE TITLE
Maybe do not report architecture?

### ISSUE THREAD

**Issue by hroncok** [fedora-python/taskotron-python-versions#13]
The naming scheme report is too much verbose for arched packages:

See http://taskotron-dev.fedoraproject.org/resultsdb/results?groups=ff46afec-4058-11e7-aa12-525400cb0b45

```

These RPMs' names violate the new Python package naming guidelines:
samba-python-4.5.10-0.fc25.armv7hl.rpm, samba-python-4.5.10-0.fc25.i686.rpm, samba-python-4.5.10-0.fc25.x86_64.rpm

Read the following document to find more information and a possible cause:
https://python-rpm-porting.readthedocs.io/en/latest/naming-scheme.html
Or ask at #fedora-python IRC channel for help.

If you think the result is false or intentional, file a bug against:
https://github.com/fedora-python/task-python-versions/issues

-----------
```

We could just drop the architectures and report:

```
These RPMs' names violate the new Python package naming guidelines:
samba-python-4.5.10-0.fc25
...
```

We could do this also in the two_three check, if desired, but somehow I think it's easier to have different architectures have different requires, than different names.

@irushchyshyn What do you think?

**Comment by irushchyshyn** [comment]
I think dropping the architecture is a way to go in this case.  Thanks for reporting, I will look into this today.
