### ISSUE TITLE
Shebangs checks

### ISSUE THREAD

**Issue by hroncok** [fedora-python/taskotron-python-versions#28]
Part of https://github.com/fedora-python/taskotron-python-versions/issues/5

Check whether package requires `/usr/bin/python` and if so, possibly check what file(s) have it in shebang.

**Comment by mcyprian** [comment]
Thanks for opening the issue @hroncok. Is in your opinion `/usr/bin/env python` also an issue? Should the check fail in this case or end with some warning (NEEDS_INSPECTION)?

**Comment by hroncok** [comment]
`/usr/bin/env python` is definitively also an issue. However, so is `/usr/bin/env python2` or `/usr/bin/env perl`, so I'd guess when there is a requirement on `/usr/bin/env`, ideally another taskotron check should report that. However, since we ar enot sure if that's happening, I suggest we report only `/usr/bin/env python*`.
