### ISSUE TITLE
New check: Is Python 3 supported upstream but not in the package?

### ISSUE THREAD

**Issue by hroncok** [fedora-python/taskotron-python-versions#33]
Let's implement a check that checks whether upstream is Python 3 ready while your package is not.

Source of data: Bugzilla, see https://github.com/fedora-python/portingdb/blob/bb1a4e789fa0b10d3e21666edfc62c75e8322e59/dnf-plugins/py3query.py#L200 and around

**Comment by irushchyshyn** [comment]
So this should basically check if the package is one of [mispackaged](http://fedora.portingdb.xyz/#mispackaged), excluding those that we check here already (depending on both Py2/Py3, missing Py3 executables), correct?
This is going to add an additional dependency on bugzilla package.

**Comment by hroncok** [comment]
More or less correct.

> This is going to add an additional dependency on bugzilla package.

OK. It's MPL licensed, so we are good.
