### ISSUE TITLE
False positives for boost packages

### ISSUE THREAD

**Issue by jwakely** [fedora-python/taskotron-python-versions#34]
https://taskotron.fedoraproject.org/artifacts/all/7213b108-a09b-11e7-9b1d-525400817a8f/task_output/output.log ays

````
These RPMs' names violate the new Python package naming guidelines:
boost-openmpi-python-1.63.0-8.fc26, boost-python-1.63.0-8.fc26, boost-mpich-python-1.63.0-8.fc26
````

This is incorrect, those are not python modules, so the names are not in violation of the guidelines.

`boost-python` is a C++ library for interfacing with Python, it's not a Python module.

`boost-openmpi-python` and `boost-mpich-python` do contain Python modules, but they primarily install C++ libraries, and a Python module that it interfaces with e.g.:

````
$ rpm -ql boost-mpich-python
/usr/lib64/mpich/lib/libboost_mpi_python.so.1.63.0
/usr/lib64/python2.7/site-packages/mpich/boost
/usr/lib64/python2.7/site-packages/mpich/boost/__init__.py
/usr/lib64/python2.7/site-packages/mpich/boost/__init__.pyc
/usr/lib64/python2.7/site-packages/mpich/boost/__init__.pyo
/usr/lib64/python2.7/site-packages/mpich/boost/mpi.so
/usr/share/licenses/boost-mpich-python
/usr/share/licenses/boost-mpich-python/LICENSE_1_0.txt
````

They are subpackages of `boost` and I think retaining that prefix makes more sense (the Python modules are not useful on their own, only in tandem with the Boost.Python C++ library).

Could these three packages please be whitelisted, so taskotron doesn't complain about them?

**Comment by hroncok** [comment]
The package name says python (not python2). It installs to `/usr/lib64/python2.7/`, so it's a Python 2 only thing. As such, this is a bug in the package name. We can bikeshed whether this package is special enough to break the prefix rule, but no package that is Python 2 specific shall be named with unqualified python in the name. Is there an equivalent package for Python 3? How is it named?

**Comment by hroncok** [comment]
boost-mpich-python3

**Comment by hroncok** [comment]
So, please rename the package to boost-mpich-python2 and then either this check stops failing, or we can continue the discussion about this being special enough to use a suffix instead of prefix.

**Comment by jwakely** [comment]
> The package name says python (not python2). It installs to `/usr/lib64/python2.7/`

`boost-python` doesn't install anything to `/usr/lib64/python2.7` 

> no package that is Python 2 specific shall be named with unqualified python in the name

That's the new guideline, but was not enforced for f26. The packages have already been renamed for f27, but is renaming them now for f26 (and setting the necessary `obsoletes` tags) appropriate for a stable release?

I think I'd rather just ignore the taskotron results for f26.

**Comment by hroncok** [comment]
> boost-python doesn't install anything to /usr/lib64/python2.7

Ok then. Whether it's boost-python2 or python2-boost is your decision, just note that with suffix, you cannot benefit from the python_provide macro.

> The packages have already been renamed for f27

Great! The [latest Koji build for f27 as well as f28](https://koji.fedoraproject.org/koji/packageinfo?packageID=1074) however still lists -python packages.

> is renaming them now for f26 (and setting the necessary obsoletes tags) appropriate for a stable release?

I agree that it's not appropriate. However the guideline was still there even for f26 (just not enforced), thus taskotron will report it as a problem. Ignoring the problem for f26 is is a reasonable choice. However, please don't ignore it for f27 and rawhide.

**Comment by jwakely** [comment]
OK thanks, let's close this then. No change needed to the taskotron tests.
