### ISSUE TITLE
The integration tests take ages (not that much anymore, but still)

### ISSUE THREAD

**Issue by hroncok** [fedora-python/taskotron-python-versions#45]
The integration tests were parallelized in https://github.com/fedora-python/taskotron-python-versions/pull/62 but this keeps open because the time is still not ideal.

Original issue follows:

----------

(Especially after https://github.com/fedora-python/taskotron-python-versions/pull/44.)

 * we check 13 koji builds, maybe we can get rid of some and reuse more of them?
 * on Travis CI, we might split the tests into groups (based on the used fixtures) and use the Build Matrix to run ~4 groups of integration tests at the same time
 * locally we could try to do the same and parallelize the tests, however when we run stuff in mock, we can only run one check at a time, so this might be very hard

**Comment by kparal** [comment]
Today I have massively sped up our test suite execution in mock from 100 seconds to 15 seconds by using `gather_facts: no` in our playbooks. See here:
https://pagure.io/taskotron/libtaskotron/c/bfa4e5de672e433db9f070d1cff94878eb5e5812

The problem is that network is disabled in mock and ansible times out when gathering certain facts. Since you don't use any facts in `tests.yml`, I suggest you try adding the same thing and compare the test suite execution time.

**Comment by hroncok** [comment]
Thanks for the tip. I'll do some testing, but our mock has networking enabled.

**Comment by hroncok** [comment]
As is (two measurements):

```
real	9m1,968s
user	6m35,021s
sys	0m27,029s
```

```
real	9m4,934s
user	6m54,039s
sys	0m28,724s

```

**Comment by hroncok** [comment]
Disabling gathering facts:

```
real	9m7,752s
user	6m47,682s
sys	0m26,951s
```

```
real	8m45,465s
user	6m32,248s
sys	0m25,697s
```

I don't think there's any difference. But I can make more measurements over night.

**Comment by kparal** [comment]
If it has networking enabled, then no, there won't be any significant speed up.

**Comment by hroncok** [comment]
I have an idea how to make the mock calls parallel runnable. If it works, we can try to run the testsuite with pytest-xdist.

**Comment by hroncok** [comment]
https://github.com/fedora-python/taskotron-python-versions/pull/62

**Comment by hroncok** [comment]
Ok, this is now better but not perfect.

**Comment by hroncok** [comment]
Closing, Taskotron goes EOL on 2020-04-30.
