### ISSUE TITLE
The task should print where it found uses of /usr/bin/python

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-python/taskotron-python-versions#49]
Greetings!

A recent Bodhi build of mine [failed](https://taskotron.fedoraproject.org/artifacts/all/acf7a06c-1b3f-11e8-9d96-525400fc9f92/task_output/output.log) the check for ```/usr/bin/python``` being used, but I am having a hard time finding what piece of Bodhi is using ```/usr/bin/python```. Could we adjust the test so that it also prints where it found an unversioned Python usage so it's easier to find and fix?

```
You've used /usr/bin/python during build on the following arches:

  bodhi-3.4.0-1.fc29: noarch

Use /usr/bin/python3 or /usr/bin/python2 explicitly.
/usr/bin/python will be removed or switched to Python 3 in the future.


Read the following document to find more information and a possible cause:
https://fedoraproject.org/wiki/Changes/Avoid_usr_bin_python_in_RPM_Build
Or ask at #fedora-python IRC channel for help.

If you think the result is false or intentional, file a bug against:
https://github.com/fedora-python/task-python-versions/issues

-----------
```

**Comment by encukou** [comment]
The check greps the [build log](https://kojipkgs.fedoraproject.org//packages/bodhi/3.4.0/1.fc29/data/logs/noarch/build.log) for a specific `DEPRECATION WARNING`. The failure message should (at least) say that.

---

In your particular case, this happens in automagic compilation of Python files outside Python-specific directories. We're preparing a [Change](https://fedoraproject.org/wiki/Changes/No_more_automagic_Python_bytecompilation) to make that saner, but alas, that's for f29.

In the meantime, you can [redefine `%__python`  to `%__python3`](https://fedoraproject.org/w/index.php?title=Packaging:Python_Appendix&oldid=419140#Manual_byte_compilation):

    %global __python %{__python3}

… and check you're not using `%{__python}` to mean Python 2 elsewhere.

**Comment by bowlofeggs** [comment]
Yeah I just noticed the same thing:

```
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Bytecompiling .py files below /builddir/build/BUILDROOT/bodhi-3.4.0-1.fc29.noarch/usr/lib/python2.7 using /usr/bin/python2.7
/builddir/build/BUILDROOT/bodhi-3.4.0-1.fc29.noarch/etc/fedmsg.d/bodhi.py
/builddir/build/BUILDROOT/bodhi-3.4.0-1.fc29.noarch/etc/fedmsg.d/masher.py
DEPRECATION WARNING: python2 invoked with /usr/bin/python.
    Use /usr/bin/python3 or /usr/bin/python2
    /usr/bin/python will be removed or switched to Python 3 in the future.
    If you cannot make the switch now, please follow instructions at https://fedoraproject.org/wiki/Changes/Avoid_usr_bin_python_in_RPM_Build#Quick_Opt-Out
DEPRECATION WARNING: python2 invoked with /usr/bin/python.
    Use /usr/bin/python3 or /usr/bin/python2
    /usr/bin/python will be removed or switched to Python 3 in the future.
    If you cannot make the switch now, please follow instructions at https://fedoraproject.org/wiki/Changes/Avoid_usr_bin_python_in_RPM_Build#Quick_Opt-Out
```

If it's difficult to have the test print the location, perhaps it would be easier to have it print a tip about looking for ```DEPRECATION WARNING``` in the build log, which should help packagers find the problem themselves more easily.

**Comment by hroncok** [comment]
> If it's difficult to have the test print the location, perhaps it would be easier to have it print a tip about looking for DEPRECATION WARNING in the build log, which should help packagers find the problem themselves more easily.

Exactly what shall be done.

**Comment by hroncok** [comment]
> We're preparing a Change to make that saner, but alas, that's for f29.

As currently planned the change will not solve this particular use case.
