### ISSUE TITLE
python-cartopy contains a common data package

### ISSUE THREAD

**Issue by QuLogic** [fedora-python/taskotron-python-versions#53]
Across both Python 2 and 3, there's a common data package `python-cartopy-common`, but it's triggering a [false warning about requiring 2 and 3](https://taskotron.fedoraproject.org/artifacts/all/3e1cc1ec-1ce6-11e8-8c58-525400fc9f92/task_output/output.log) for the Python3 version.

Similar to #6 in that it would need an exception (or a suggestion for a better name).

**Comment by hroncok** [comment]
Thanks for the report. The name is fine, please keep it.
