### ISSUE TITLE
Tests incorrectly indentifies python-jupyter-filesystem as a python 2 package.

### ISSUE THREAD

**Issue by ellert** [fedora-python/taskotron-python-versions#64]
The tests for the update
https://bodhi.fedoraproject.org/updates/FEDORA-2018-3fe9e5e2f1
has false positives for the dist.python-versions and dist.python-versions.two_three tests

The test logs say:

These RPMs require both Python 2 and Python 3:
python3-ipyparallel-6.2.1-1.fc28.noarch.rpm
 * Python 2 dependency: python-jupyter-filesystem
 * Python 3 dependecny: python(abi) = 3.6

But python-jupyter-filesystem is not a python 2 package (nor is it a python 3 package). The package only contain directories so that package installing files in these directories can depend on this package instead of owning the directories. None of the directories in the package is neither python 2 nor python 3 specific.

**Comment by hroncok** [comment]
I've immediately pushed https://github.com/fedora-python/taskotron-python-versions/commit/eca43d33d4057861e6e3caaabf6eec4cd729f055 but it hasn't yet been pushed to master.

**Comment by hroncok** [comment]
It passed on devel: http://taskotron-dev.fedoraproject.org/resultsdb/results/20719730

**Comment by hroncok** [comment]
Merged to master.
