### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by kparal** [fedora-python/taskotron-python-versions#86]
```
DEBUG:python-versions:Checking python-sphinx-click-doc-2.2.0-1.fc31.noarch.rpm
Traceback (most recent call last):
  File "python_versions_check.py", line 126, in <module>
    arches=arches)
  File "python_versions_check.py", line 74, in run
    details.append(task_two_three(packages, koji_build, artifact))
  File "/var/tmp/taskotron/taskdir/taskotron_python_versions/two_three.py", line 124, in task_two_three
    name, py_versions = check_two_three(package)
  File "/var/tmp/taskotron/taskdir/taskotron_python_versions/two_three.py", line 86, in check_two_three
    for nevr in package.require_nevrs:
  File "/var/tmp/taskotron/taskdir/taskotron_python_versions/common.py", line 117, in require_nevrs
    return [r.decode() for r in self.hdr[rpm.RPMTAG_REQUIRENEVRS]]
  File "/var/tmp/taskotron/taskdir/taskotron_python_versions/common.py", line 117, in <listcomp>
    return [r.decode() for r in self.hdr[rpm.RPMTAG_REQUIRENEVRS]]
AttributeError: 'str' object has no attribute 'decode'
```
https://taskotron.fedoraproject.org/artifacts/all/8ad61b30-966d-11e9-bcba-52540077ca13/tests.yml/test.log.gz

**Comment by kparal** [comment]
I think there might have been some change in rpm bindings lately which change the returned objects. Here are the versions of used libraries:
https://taskotron.fedoraproject.org/artifacts/all/ac4e5058-9658-11e9-a964-52540077ca13/tests.yml/taskotron/rpm-qa.log.gz

**Comment by hroncok** [comment]
Yes, this is the API change in rpm Python bindings. Thanks for the report, I'll try to fix this. However, the rwahide docker image has not yet been updated, so the CI is useless here. LEt em try to stick a `dnf update` call somewhere there.

**Comment by hroncok** [comment]
Working on this in https://github.com/fedora-python/taskotron-python-versions/pull/87

**Comment by kparal** [comment]
Huh, I just noticed, we're not supposed to be running Taskotron tasks on Rawhide, but we clearly are. I'll find out what went wrong, and the crashes will hopefully go away once we run on F30 again.

**Comment by hroncok** [comment]
Either way we test on rawhide as well and the failure just got reproduced on the CI. A fix is trivial.
